GrapeSwaggerRails.options.url = 'api/swagger_doc'
GrapeSwaggerRails.options.app_name = 'Mobile'
GrapeSwaggerRails.options.app_url  = '/'
GrapeSwaggerRails.options.api_key_name = 'auth_key'
GrapeSwaggerRails.options.api_key_type = 'query'
